### ISSUE TITLE
想備份ポカ的Blog...

### ISSUE THREAD

**Issue by Damppopcorn** [teddy8997/Hinatazaka46_Blog_backup_tool#1]
ポカ的部落格沒辦法更新，求解！(ポカ代號：000)
![20230501](https://user-images.githubusercontent.com/100677602/235363975-2ffebd3a-aedd-47e9-a11d-3b4e3da64475.jpg)

**Comment by teddy8997** [comment]
已更新程式碼，請使用新的程式碼。
新增可備份=> 四期生リレー 以及 ポカ 的部落格
選擇成員請貼上四期生リレー 或 ポカ
