### ISSUE TITLE
高本彩花的BLOG未能完整下載

### ISSUE THREAD

**Issue by dickson870** [teddy8997/Hinatazaka46_Blog_backup_tool#3]
你好,感謝你的python腳本讓我可以備份京子的BLOG

現在想備份高本彩花的BLOG時發現去到2021.12.28時會強制停止

請問是不是有那裡可以修正的地方?

謝謝

**Comment by teddy8997** [comment]
已經修正，請用240701Hinatazaka46_Blog_backup.py版本備份，謝謝。

**Comment by dickson870** [comment]
> 已經修正，請用240701Hinatazaka46_Blog_backup.py版本備份，謝謝。

感謝修正!

另有一事相求 可否寫一個Nogizaka46的python腳本?

功德無量
